### ISSUE TITLE
CatBoostRanker.score is broken 

### ISSUE THREAD

**Issue by dmitrySorokin** [catboost/catboost#2230]
Problem: CatBoostRanker.score is broken 
```
ranker.score(X_test, y_test, group_test)
TypeError: get_ndcg_metric_name() missing 2 required positional arguments: 'values' and 'names'
```
Parameters 'values' and 'names' are [required](https://github.com/catboost/catboost/blob/a0651585cd2e5fa87a02792e9c529d6023da0abb/catboost/python-package/catboost/core.py#L6212) but not [supplied](https://github.com/catboost/catboost/blob/a0651585cd2e5fa87a02792e9c529d6023da0abb/catboost/python-package/catboost/core.py#L6231).  

catboost version: 1.0.3
Operating System: Macos
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: -

Probably broken by a01d0168537 commit.

**Comment by dmitrySorokin** [comment]
https://github.com/catboost/catboost/pull/2231

**Comment by andrey-khropov** [comment]
Fix included in the release 1.2
