### ISSUE TITLE
0.9.1.1 build fails for Gentoo Linux (GCC 6.4.0, 7.3.0, CUDA 9.2)

### ISSUE THREAD

**Issue by lutel** [catboost/catboost#410]
Problem: Unable to build from source with GPU support (CPU version builds fine)
catboost version: 0.9.1.1
Operating System: Gentoo Linux
CPU: Xeon(R) CPU E3-1240
1 GPU:  GeForce GTX 750 (capability 5.0)

**# python mk_wheel.py -DCUDA_ROOT="/opt/cuda"**
`Trying to build GPU version
/usr/lib/python-exec/python3.6/python /w/pip/catboost/ya make /w/pip/catboost/catboost/python-package/catboost --no-src-links -r --output /tmp/tmpd5bt4hcv -DPYTHON_CONFIG=python3-config -DNO_DEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DCUDA_ROOT=/opt/cuda -DHAVE_CUDA=yes
------- [CC] {pic, FAILED} $(S)/catboost/cuda/cuda_lib/kernel/reduce.cu
command /pip/.ya/tools/v3/173608153/python /w/pip/catboost/build/scripts/compile_cuda.py /opt/cuda/bin/nvcc -std=c++14 --expt-relaxed-constexpr -gencode arch=compute_30,code=compute_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=compute_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=compute_60 -gencode arch=compute_61,code=compute_61 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 --ptxas-options=-v -c /w/pip/catboost/catboost/cuda/cuda_lib/kernel/reduce.cu -o /pip/.ya/build/build_root/hiay/000098/catboost/cuda/cuda_lib/kernel/reduce.cu.o -I/pip/.ya/build/build_root/hiay/000098 -I/w/pip/catboost -I/w/pip/catboost/contrib/libs/cxxsupp/libcxxrt -I/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include -I/w/pip/catboost/contrib/libs/double-conversion/include -I/w/pip/catboost/contrib/libs/libf2c --cflags --target=x86_64-linux-gnu -B$OS_SDK_ROOT_RESOURCE_GLOBAL/usr/bin -pipe -m64 -msse -msse3 -msse2 -O2 -Wno-inconsistent-missing-override -Wno-c++17-extensions -Wno-exceptions -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -D_GNU_SOURCE -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-error=deprecated -fPIC -DCATBOOST_OPENSOURCE=yes -I/opt/cuda/include -nostdinc++ -DFAKEID=3772858 -DARCADIA_ROOT=/w/pip/catboost -DARCADIA_BUILD_ROOT=/pip/.ya/build/build_root/hiay/000098 failed with exit code 1
cc1plus: warning: command line option '-ftarget=x86_64-linux-gnu' is valid for Java but not for C++
cc1plus: warning: unrecognized command line option '-Wno-exceptions'
cc1plus: warning: unrecognized command line option '-Wno-inconsistent-missing-override'
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h(38): error: namespace "std" has no member "abort"

/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h(39): error: namespace "std" has no member "atexit"

/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdlib.h(40): error: namespace "std" has no member "exit"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/stdlib.h(119): error: identifier "labs" is undefined

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/stdlib.h(121): error: identifier "llabs" is undefined

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/stdlib.h(124): error: identifier "ldiv_t" is undefined

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/stdlib.h(124): error: identifier "ldiv" is undefined

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/stdlib.h(126): error: identifier "lldiv_t" is undefined

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/stdlib.h(126): error: identifier "lldiv" is undefined

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(101): error: the global scope has no "div_t"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(102): error: the global scope has no "ldiv_t"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(104): error: the global scope has no "lldiv_t"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(106): error: the global scope has no "atof"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(107): error: the global scope has no "atoi"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(108): error: the global scope has no "atol"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(110): error: the global scope has no "atoll"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(112): error: the global scope has no "strtod"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(113): error: the global scope has no "strtof"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(114): error: the global scope has no "strtold"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(115): error: the global scope has no "strtol"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(117): error: the global scope has no "strtoll"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(119): error: the global scope has no "strtoul"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(121): error: the global scope has no "strtoull"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(123): error: the global scope has no "rand"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(124): error: the global scope has no "srand"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(125): error: the global scope has no "calloc"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(126): error: the global scope has no "free"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(127): error: the global scope has no "malloc"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(128): error: the global scope has no "realloc"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(129): error: the global scope has no "abort"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(130): error: the global scope has no "atexit"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(131): error: the global scope has no "exit"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(132): error: the global scope has no "_Exit"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(134): error: the global scope has no "getenv"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(135): error: the global scope has no "system"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(137): error: the global scope has no "bsearch"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(138): error: the global scope has no "qsort"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(140): error: the global scope has no "labs"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(142): error: the global scope has no "llabs"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(145): error: the global scope has no "ldiv"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(147): error: the global scope has no "lldiv"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(149): error: the global scope has no "mblen"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(150): error: the global scope has no "mbtowc"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(151): error: the global scope has no "wctomb"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(152): error: the global scope has no "mbstowcs"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cstdlib(153): error: the global scope has no "wcstombs"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(313): error: the global scope has no "signbit"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(314): error: the global scope has no "fpclassify"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(315): error: the global scope has no "isfinite"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(316): error: the global scope has no "isinf"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(317): error: the global scope has no "isnan"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(318): error: the global scope has no "isnormal"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(319): error: the global scope has no "isgreater"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(320): error: the global scope has no "isgreaterequal"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(321): error: the global scope has no "isless"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(322): error: the global scope has no "islessequal"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(323): error: the global scope has no "islessgreater"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(324): error: the global scope has no "isunordered"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(325): error: the global scope has no "isunordered"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(327): error: the global scope has no "float_t"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(328): error: the global scope has no "double_t"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(445): error: the global scope has no "nexttoward"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(446): error: the global scope has no "nexttowardf"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(464): error: the global scope has no "acosl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(465): error: the global scope has no "asinl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(466): error: the global scope has no "atanl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(467): error: the global scope has no "atan2l"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(468): error: the global scope has no "ceill"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(469): error: the global scope has no "cosl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(470): error: the global scope has no "coshl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(471): error: the global scope has no "expl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(472): error: the global scope has no "fabsl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(473): error: the global scope has no "floorl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(474): error: the global scope has no "fmodl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(475): error: the global scope has no "frexpl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(476): error: the global scope has no "ldexpl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(477): error: the global scope has no "logl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(478): error: the global scope has no "log10l"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(479): error: the global scope has no "modfl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(480): error: the global scope has no "powl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(481): error: the global scope has no "sinl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(482): error: the global scope has no "sinhl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(483): error: the global scope has no "sqrtl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(484): error: the global scope has no "tanl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(486): error: the global scope has no "tanhl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(487): error: the global scope has no "acoshl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(488): error: the global scope has no "asinhl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(489): error: the global scope has no "atanhl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(490): error: the global scope has no "cbrtl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(492): error: the global scope has no "copysignl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(494): error: the global scope has no "erfl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(495): error: the global scope has no "erfcl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(496): error: the global scope has no "exp2l"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(497): error: the global scope has no "expm1l"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(498): error: the global scope has no "fdiml"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(499): error: the global scope has no "fmal"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(500): error: the global scope has no "fmaxl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(501): error: the global scope has no "fminl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(502): error: the global scope has no "hypotl"

/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/cmath(503): error: the global scope has no "ilogbl"

Error limit reached.
100 errors detected in the compilation of "/pip/.ya/tmp/1531292609.26099.w8hyxy46/tmpxft_00006631_00000000-12_reduce.compute_70.cpp1.ii".
Compilation terminated.
Failed`

**Comment by Paperone80** [comment]
Hi, 

Had similar problems but compilation with GPUworked for me as I described here in Issue [386](https://github.com/catboost/catboost/issues/386). Hope that helps.

**Comment by annaveronika** [comment]
Everything should work with latest version on github. Please try building with the latest version.
I'm closing the issue, please, feel free to reopen if something doesn't work for you.

**Comment by lutel** [comment]
> Hi,
> 
> Had similar problems but compilation with GPUworked for me as I described here in Issue [386](https://github.com/catboost/catboost/issues/386). Hope that helps.

Thank you, unfortunately it doesn't help as I can't compile it with GCC.

**Comment by Paperone80** [comment]
@lutel, do you have the possibility to try it with GCC 5.5? Also, I am using CUDA 9.0 because of Tensorflows requirements: [here](https://www.tensorflow.org/install/gpu). These are my settings which worked, **so change your paths accordingly**:
`$ su`
`$ ../../../ya make -r -v -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/opt/intel/intelpython35/bin/python3-config -DCUDA_ROOT=/usr/local/cuda -DPYTHON_INCLUDE=“-I/opt/intel/intelpython35/include/python3.5m” -DPYTHON_LIBRARIES=/opt/intel/intelpython35/lib -DPYTHON_BIN=/opt/intel/intelpython35/bin -DCUDA_NVCC_FLAGS="-ccbin /opt/gcc/GCC-5.5.0/bin/gcc"`

Use the same GCC to also build the Wheel package:
`$ cd /opt/catboost/catboost_2018-08-03/catboost/python-package`
`$ /opt/intel/intelpython35/bin/python3.5 mk_wheel.py -DPYTHON_INCLUDE="-I/opt/intel/intelpython35/include/python3.5m" -DPYTHON_LIBRARIES="/opt/intel/intelpython35/lib" -DCUDA_ROOT=/usr/local/cuda -DCUDA_NVCC_FLAGS="-ccbin /opt/gcc/GCC-5.5.0/bin/gcc"`

Good luck!

**Comment by lutel** [comment]
@Paperone80 thank you, but I can't install GCC 5.5 - either 6.3 or 7.3. I have CUDA 9.2.  Tried to build with 7.3, filtered out --target flag from script:

python mk_wheel.py -DCUDA_ROOT="/opt/cuda" -DCUDA_NVCC_FLAGS="-ccbin /usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0/gcc"

I got different errors:

/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/stdlib.h(38): error: namespace "std" has no member "abort"
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/stdlib.h(39): error: namespace "std" has no member "atexit"
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/stdlib.h(40): error: namespace "std" has no member "exit"
/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/stdlib.h(119): error: identifier "labs" is undefined
/w/pip/catboost/contrib/libs/cxxsupp/libcxx/include/stdlib.h(121): error: identifier "llabs" is undefined

**Comment by Paperone80** [comment]
@lutel, just tried to compile the latest Catboost v0.10.2 with GCC 6.4.0. No luck. Tried with GCC 5.5.0 and it worked. If you have the chance compile GCC 5.5.0 yourself in /opt. Here is what worked for me:
Overall directory structure in
/opt/gcc/
- build_gcc-5.5.0 (objdir)
- gcc-5.5.0 (source_dir)
- GCC-5.5.0 (--prefix=destdir) for ‘make install’ 

Download GCC and decompress into /opt/gcc/gcc-5.5.0:
```
$ su
$ mkdir -p /opt/gcc
$ cd /opt/gcc
$ wget [https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.gz](https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.gz)
$ tar xzf gcc-5.5.0.tar.gz
$ cd gcc-5.5.0
$ ./contrib/download_prerequisites
```

Compile from directory /opt/gcc/build_gcc-5.5.0:
```
$ mkdir -p /opt/gcc/build_gcc-5.5.0
$ cd /opt/gcc/build_gcc-5.5.0
$ /opt/gcc/gcc-5.5.0/configure --prefix=/opt/gcc/GCC-5.5.0 --enable-languages=c,c++,objc,obj-c++,lto --enable-bootstrap --with-build-config='bootstrap-lto bootstrap-O3' --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --enable-multiarch
$ make -j16 PREFIX=/opt/gcc/GCC-5.5.0
$ make install
```
....
you should see ...
```
Libraries have been installed in:
   /opt/gcc/GCC-5.5.0/lib/../lib64
…
Libraries have been installed in:
   /opt/gcc/GCC-5.5.0/lib/../lib
….
```
Test binaries with with:
`$ /opt/gcc/GCC-5.5.0/bin/gcc -v`

Now you can use the gcc binary to link in the Catboost NVCC statement.

**Comment by lutel** [comment]
Thanks, I could build it with GCC 5.5, however I can't make it work - is it compatibile with CUDA 9.2?

_catboost.CatboostError: catboost/libs/train_lib/train_model.cpp:815: Can't load GPU learning library. Module was not compiled or driver  is incompatible with package. Please install latest NVDIA driver and check again

**Comment by annaveronika** [comment]
You cannot build with gcc, you need clang. We are currently working on building with clang instead of system compiler, so hopefully soon you will not see this problem.

**Comment by Paperone80** [comment]
@lutel , @annaveronika, I checked and compiling for GPU with CUDA NVCC using flag 
`-DCUDA_NVCC_FLAGS="-ccbin /opt/gcc/GCC-5.5.0/bin/gcc"` works for me with CUDA 9.0 . 

@lutel, if you are using Python try:
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import catboost.gpu._catboost
from catboost import CatBoost, CatBoostClassifier, CatBoostRegressor
catboost.__version__
```

> 0.10.2

If you have multiple GPUs check with the following command and choose CUDA_VISIBLE_DEVICES (in my case '0'-TITAN X) accordingly.
`$ nvidia-smi -L`

> GPU 0: TITAN X (Pascal) 
> GPU 1: Quadro 2000

**Comment by lutel** [comment]
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import catboost.gpu._catboost
from catboost import CatBoost, CatBoostClassifier, CatBoostRegressor
catboost.__version__

> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     import catboost.gpu._catboost
> ModuleNotFoundError: No module named 'catboost.gpu'

**Comment by Paperone80** [comment]
@lutel, did you install the resulted wheel correctly?
In the catboost directory. (Change to your python path which you used when compiling) 
```
$ cd catboost/python-package
$ /opt/intel/intelpython35/bin/pip install catboost-0.10.2-cp35-none-manylinux1_x86_64.whl 
```
Check with your python pip whether catboost is installed
`$ <your python bin path>pip list | grep catboost`

Also, in python make sure using with .__version__
catboost.__version__

**Comment by lutel** [comment]
Finally I found it was old installation (without GPU support). Now it works fine, although I had to remove enum for Python 3.6.
